CraigsList/CraigsList/Models/Apartments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CraigsList.Models
{
    public class Apartments : Ads
    {
        public string BedsBaths { get; set; }
        public int SquareFootage { get; set; }
        public bool Animals { get; set; }

    }
}

CraigsList/CraigsList/Controllers/ApartmentsController.cs
using CraigsList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CraigsList.Controllers
{
    public class ApartmentsController : Controller
    {
        // GET: Apartments
        public ActionResult Index()
        {
            AdsVm cVm = new AdsVm();
            cVm.AptAds = MockDB.GetApartments();
            return View(cVm);
        }

        public ActionResult Details(int id)
        {
            AdsObjVm cVm = new AdsObjVm();
            cVm.Apt = MockDB.GetApartments().FirstOrDefault(i => i.Id == id);
            return View(cVm);
        }
    }
}

CraigsList/CraigsList/Views/Apartments/Details.cshtml
@model CraigsList.Models.AdsObjVm

@{
    
}

<br /><br />
<div>
    <p>@Model.Apt.CreatedBy, @Model.Apt.Title</p>
    <br />
    <p>Availible: @Model.Apt.IsAvailible</p>
</div>

CraigsList/CraigsList/Views/Apartments/Index.cshtml
@model CraigsList.Models.AdsVm

@{
    
}


<div class="col-md-12">
    <h2>Apartments</h2>
    <table class="table-responsive table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Created By</th>
                <th>Created On</th>
                <th>City</th>
                <th>State</th>
                <th>Availibility</th>
                <th>Price</th>
                <th>BedsBaths</th>
                <th>SquareFootage</th>
                <th>Animals</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var k in Model.AptAds)
            {
                <tr>
                    <td>@k.Id</td>
                    <td>@k.Title</td>
                    <td>@k.CreatedBy</td>
                    <td>@k.CreatedOn</td>
                    <td>@k.City</td>
                    <td>@k.State</td>
                    <td>@k.IsAvailible</td>
                    <td>$@k.Price</td>
                    <td>@k.BedsBaths</td>
                    <td>@k.SquareFootage</td>
                    <td>@k.Animals</td>
                    <td>@Html.ActionLink("Details", "Details", "Apartments", new { Id = k.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
</div>